set "PATH=c:\Programs\CMake\bin\"
Urho3D/cmake_vs2015.bat Build -DURHO3D_OPENGL=ON -DURHO3D_STATIC_RUNTIME=ON -DURHO3D_ANGELSCRIPT=ON -DURHO3D_SAMPLES=OFF -DURHO3D_LUA=OFF -DURHO3D_NETWORK=OFF -DURHO3D_PHYSICS=OFF -DURHO3D_NAVIGATION=OFF -DURHO3D_URHO2D=OFF
pause
